---
language: ruby

dist: trusty
sudo: false

before_install:
  - rvm get head
  - gem install bundler
  - export CXX="g++-4.8"

addons:
 apt:
  sources:
  - ubuntu-toolchain-r-test
  packages:
  - g++-4.8

rvm:
  - 2.2.4
  - 2.3.1
  - ruby-head
  - rbx
  - jruby-9.1.0.0
  - jruby-head

script: ./.travis.sh

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx

notifications:
  recipients:
    - mail@zzak.io
  slack: sinatrarb:LQGhUfGYcqRgRzwKea0bqUhY
