---
language: ruby

dist: xenial

before_install:
  - gem install bundler
  - export CXX="g++-4.8"

addons:
 apt:
  sources:
  - ubuntu-toolchain-r-test
  packages:
  - g++-4.8
  - pandoc
rvm:
  - 2.3.8
  - 2.4.10
  - 2.5.8
  - 2.6.6
  - 2.7.1
  - 3.0.0
  - jruby-9.2.15.0

script: ./.travis.sh

matrix:
  allow_failures:
    - rvm: jruby-9.2.15.0

notifications:
  slack:
    secure: 6E+GuZId5GcVLgiOKZnE9ZAnJTa+K2Fxqb0KfrECtskviylcPF1OmX36+y7xGUS0P0pGNyWQThe0zCBMpszno/KbvUdIs6jXbOImkFMuo65//4YcivK0rVaYh9uh2S1K3ycaDeUPDf0ulc/AwHnxWGR6yBD2N5idTwt1bsULdy0=
