---
language: ruby

dist: trusty
sudo: true

before_install:
  - rvm get head
  - gem install bundler
  - export CXX="g++-4.8"
  
addons:
 apt:
  sources:
  - ubuntu-toolchain-r-test
  packages:
  - g++-4.8

rvm:
  - 2.2.4
  - 2.3.1
  - ruby-head
  - rbx-2
  - jruby-9.1.0.0
  - jruby-head

sudo: false

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-2

notifications:
  recipients:
    - mail@zzak.io
  slack: sinatrarb:LQGhUfGYcqRgRzwKea0bqUhY
