rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - rbx-18mode
  - rbx-19mode
  - jruby-18mode
  - jruby-19mode
  - jruby-head
  - ruby-head
env:
  - "rack=1.3.6"
  - "rack=1.4.1"
  - "rack=master"
  - "tilt=1.3.3"
  - "tilt=master"
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
notifications:
  recipients:
    - k.haase@finn.de
