---
language: ruby

dist: trusty

before_install:
  - gem install bundler
  - export CXX="g++-4.8"

addons:
 apt:
  sources:
  - ubuntu-toolchain-r-test
  packages:
  - g++-4.8
  - pandoc
rvm:
  - 2.3.8
  - 2.4.9
  - 2.5.7
  - 2.6.5
  - ruby-head
  - rbx-3
  - jruby-9.2.11.0
  - jruby-head

script: ./.travis.sh

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: jruby-9.2.11.0
    - rvm: rbx-3

notifications:
  slack:
    secure: 6E+GuZId5GcVLgiOKZnE9ZAnJTa+K2Fxqb0KfrECtskviylcPF1OmX36+y7xGUS0P0pGNyWQThe0zCBMpszno/KbvUdIs6jXbOImkFMuo65//4YcivK0rVaYh9uh2S1K3ycaDeUPDf0ulc/AwHnxWGR6yBD2N5idTwt1bsULdy0=
