---
rvm:
- 1.8.7
- 1.9.2
- 1.9.3
- rbx-18mode
- rbx-19mode
- jruby
- ruby-head
env:
- rack=1.3.0
- rack=master
- tilt=1.3.2
- tilt=master
- sinatra=master
notifications:
  recipients:
  - k.haase@finn.de
  - ohhgabriel@gmail.com
  - inbox@trevorbramble.com
